export const authContent = {
  loginTitle: "Logowanie",
  loginRequiredTitle: "Logowanie wymagane",
  loginRequiredDesc: "Zaloguj się, aby dodawać ulubione miejsca i zapisywać historię wizyt.",
  loginRequiredFavoriteDesc: "Zaloguj się, aby dodać to miejsce do swojej listy ulubionych.",
  loginRequiredVisitDesc: "Zaloguj się, aby zapisać to miejsce w swojej historii wizyt.",
  connecting: "Łączenie z systemem...",
  loginSuccess: "Zalogowano pomyślnie!",
  loginSuccessDev: "Zalogowano pomyślnie w trybie deweloperskim!",
  logoutSuccess: "Wylogowano pomyślnie.",
  loginFailed: "Zalogowanie nie powiodło się.",
  googleUnavailable: "Logowanie Google jest tymczasowo niedostępne.",
  googleInitFailed: "Nie udało się zainicjować logowania Google.",
  accountLinkRequired: "Konto o podanym adresie e-mail już istnieje w systemie, ale nie zostało połączone z kontem Google. Zaloguj się tradycyjnym hasłem w panelu administracyjnym.",
  devModeTitle: "Tryb Deweloperski (E2E / Test)",
  devBypassButton: "Bypass Login (Fake User)",
  devBypassButtonShort: "Bypass Login & Wykonaj",
  cancel: "Anuluj",
  validationError: "Błąd walidacji.",
  notActive: "Konto użytkownika jest nieaktywne.",
  rateLimited: "Zbyt wiele prób logowania. Spróbuj ponownie później.",
}
