# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    rate_limiter:
        place_search:
            policy: token_bucket
            limit: 60
            rate: { interval: '1 minute', amount: 60 }
        map_places:
            policy: token_bucket
            limit: 30
            rate: { interval: '1 minute', amount: 30 }

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
