// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthLiveData, GetHealthLiveResponses, GetHealthReadyData, GetHealthReadyErrors, GetHealthReadyResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Liveness probe
 *
 * Checks process availability without contacting dependencies.
 */
export const getHealthLive = <ThrowOnError extends boolean = false>(options?: Options<GetHealthLiveData, ThrowOnError>): RequestResult<GetHealthLiveResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthLiveResponses, unknown, ThrowOnError>({ url: '/api/v1/health/live', ...options });

/**
 * Readiness probe
 *
 * Checks the required PostgreSQL dependency; optional Redis is excluded.
 */
export const getHealthReady = <ThrowOnError extends boolean = false>(options?: Options<GetHealthReadyData, ThrowOnError>): RequestResult<GetHealthReadyResponses, GetHealthReadyErrors, ThrowOnError> => (options?.client ?? client).get<GetHealthReadyResponses, GetHealthReadyErrors, ThrowOnError>({ url: '/api/v1/health/ready', ...options });
