// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type LoginWithGoogleData = {
    /**
     * Google ID token.
     */
    body?: {
        credential: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/google';
};

export type LoginWithGoogleErrors = {
    /**
     * Invalid Google credential.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Account link required.
     */
    409: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type LoginWithGoogleError = LoginWithGoogleErrors[keyof LoginWithGoogleErrors];

export type LoginWithGoogleResponses = {
    /**
     * Successfully authenticated.
     */
    200: {
        authenticated: boolean;
        user: {
            id: string;
            displayName: string;
            initials: string;
            roles: Array<string>;
        } | null;
        csrfToken: string | null;
    };
};

export type LoginWithGoogleResponse = LoginWithGoogleResponses[keyof LoginWithGoogleResponses];

export type LoginWithDevAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dev-auth/login';
};

export type LoginWithDevAuthErrors = {
    /**
     * Not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type LoginWithDevAuthError = LoginWithDevAuthErrors[keyof LoginWithDevAuthErrors];

export type LoginWithDevAuthResponses = {
    /**
     * Successfully authenticated.
     */
    200: {
        authenticated: boolean;
        user: {
            id: string;
            displayName: string;
            initials: string;
            roles: Array<string>;
        } | null;
        csrfToken: string | null;
    };
};

export type LoginWithDevAuthResponse = LoginWithDevAuthResponses[keyof LoginWithDevAuthResponses];

export type GetAmenitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/amenities';
};

export type GetAmenitiesResponses = {
    /**
     * Reference collection.
     */
    200: {
        items: Array<{
            id: string;
            name: string;
            slug: string;
            icon_key: string;
            display_order: number;
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        meta: {
            [key: string]: unknown;
        };
    };
};

export type GetAmenitiesResponse = GetAmenitiesResponses[keyof GetAmenitiesResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/categories';
};

export type GetCategoriesResponses = {
    /**
     * Reference collection.
     */
    200: {
        items: Array<{
            id: string;
            name: string;
            slug: string;
            icon_key: string;
            display_order: number;
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        meta: {
            [key: string]: unknown;
        };
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type GetCitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cities';
};

export type GetCitiesResponses = {
    /**
     * Reference collection.
     */
    200: {
        items: Array<{
            id: string;
            name: string;
            slug: string;
            country_code: string;
            default_zoom: number;
            default_radius_km: number;
            timezone: string;
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        meta: {
            [key: string]: unknown;
        };
    };
};

export type GetCitiesResponse = GetCitiesResponses[keyof GetCitiesResponses];

export type GetMapPlacesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * west filter.
         */
        west: number;
        /**
         * south filter.
         */
        south: number;
        /**
         * east filter.
         */
        east: number;
        /**
         * north filter.
         */
        north: number;
        /**
         * zoom filter.
         */
        zoom: number;
        /**
         * city filter.
         */
        city?: string;
        /**
         * category filter.
         */
        category?: string;
        /**
         * ageMonths filter.
         */
        ageMonths?: number;
        /**
         * latitude filter.
         */
        latitude?: number;
        /**
         * longitude filter.
         */
        longitude?: number;
        /**
         * radiusKm filter.
         */
        radiusKm?: number;
        /**
         * amenities filter.
         */
        amenities?: Array<string>;
        /**
         * indoor filter.
         */
        indoor?: boolean;
        /**
         * outdoor filter.
         */
        outdoor?: boolean;
        /**
         * freeEntry filter.
         */
        freeEntry?: boolean;
        /**
         * openNow filter.
         */
        openNow?: boolean;
        /**
         * q filter.
         */
        q?: string;
        /**
         * page filter.
         */
        page?: number;
        /**
         * pageSize filter.
         */
        pageSize?: number;
        /**
         * sort filter.
         */
        sort?: string;
    };
    url: '/api/v1/map/places';
};

export type GetMapPlacesErrors = {
    /**
     * RFC 9457 invalid_query Problem Details.
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * RFC 9457 rate_limit_exceeded Problem Details with Retry-After.
     */
    429: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type GetMapPlacesError = GetMapPlacesErrors[keyof GetMapPlacesErrors];

export type GetMapPlacesResponses = {
    /**
     * GeoJSON FeatureCollection, at most 500 features.
     */
    200: {
        type: 'FeatureCollection';
        truncated: boolean;
        features: Array<{
            type: 'Feature';
            geometry: {
                type?: string;
                coordinates?: [
                    number,
                    number
                ];
            };
            properties: {
                slug: string;
                name: string;
                indoor: boolean;
                outdoor: boolean;
                freeEntry: boolean;
            };
        }>;
    };
};

export type GetMapPlacesResponse = GetMapPlacesResponses[keyof GetMapPlacesResponses];

export type SearchPlacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * city filter.
         */
        city?: string;
        /**
         * category filter.
         */
        category?: string;
        /**
         * ageMonths filter.
         */
        ageMonths?: number;
        /**
         * latitude filter.
         */
        latitude?: number;
        /**
         * longitude filter.
         */
        longitude?: number;
        /**
         * radiusKm filter.
         */
        radiusKm?: number;
        /**
         * amenities filter.
         */
        amenities?: Array<string>;
        /**
         * indoor filter.
         */
        indoor?: boolean;
        /**
         * outdoor filter.
         */
        outdoor?: boolean;
        /**
         * freeEntry filter.
         */
        freeEntry?: boolean;
        /**
         * openNow filter.
         */
        openNow?: boolean;
        /**
         * q filter.
         */
        q?: string;
        /**
         * page filter.
         */
        page?: number;
        /**
         * pageSize filter.
         */
        pageSize?: number;
        /**
         * sort filter.
         */
        sort?: string;
    };
    url: '/api/v1/places';
};

export type SearchPlacesErrors = {
    /**
     * RFC 9457 invalid_query Problem Details.
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * RFC 9457 rate_limit_exceeded Problem Details with Retry-After.
     */
    429: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type SearchPlacesError = SearchPlacesErrors[keyof SearchPlacesErrors];

export type SearchPlacesResponses = {
    /**
     * Paginated place cards.
     */
    200: {
        items: Array<{
            id: string;
            slug: string;
            name: string;
            short_description: string;
            city: string;
            categories: Array<{
                slug: string;
                name: string;
            }>;
            min_age_months: number;
            max_age_months: number | null;
            indoor: boolean;
            outdoor: boolean;
            free_entry: boolean;
            verification_status: string;
            amenities: Array<{
                slug: string;
                name: string;
            }>;
            distance_meters: number | null;
            longitude: number;
            latitude: number;
            is_open_now: boolean | null;
            complete: boolean;
            relevance_score: number;
            main_photo?: {
                thumbnail_mini?: string;
                thumbnail?: string;
                card?: string;
                hero?: string;
                original_max?: string;
            } | null;
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        meta: {
            sort: string;
        };
    };
};

export type SearchPlacesResponse = SearchPlacesResponses[keyof SearchPlacesResponses];

export type GetPlaceBySlugData = {
    body?: never;
    path: {
        /**
         * Published place slug.
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/places/{slug}';
};

export type GetPlaceBySlugErrors = {
    /**
     * RFC 9457 place_not_found Problem Details.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type GetPlaceBySlugError = GetPlaceBySlugErrors[keyof GetPlaceBySlugErrors];

export type GetPlaceBySlugResponses = {
    /**
     * Published place details.
     */
    200: {
        id: string;
        slug: string;
        name: string;
        short_description: string;
        description: string;
        city_name: string;
        city_slug: string;
        address_line1: string;
        address_line2: string | null;
        postal_code: string;
        country_code: string;
        categories: Array<{
            slug: string;
            name: string;
        }>;
        amenities: Array<{
            slug: string;
            name: string;
        }>;
        age_zones: Array<{
            [key: string]: unknown;
        }>;
        weekly_opening: Array<{
            [key: string]: unknown;
        }>;
        special_opening: Array<{
            [key: string]: unknown;
        }>;
        indoor: boolean;
        outdoor: boolean;
        free_entry: boolean;
        price_description: string | null;
        website_url: string | null;
        phone: string | null;
        verification_status: string;
        longitude: number;
        latitude: number;
        main_photo?: {
            thumbnail_mini?: string;
            thumbnail?: string;
            card?: string;
            hero?: string;
            original_max?: string;
        } | null;
        photos?: Array<{
            id?: string;
            is_main?: boolean;
            alt_text?: string | null;
            caption?: string | null;
            variants?: {
                thumbnail_mini?: string;
                thumbnail?: string;
                card?: string;
                hero?: string;
                original_max?: string;
            };
        }>;
    };
};

export type GetPlaceBySlugResponse = GetPlaceBySlugResponses[keyof GetPlaceBySlugResponses];

export type GetHealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type GetHealthLiveResponses = {
    /**
     * The API process is alive.
     */
    200: unknown;
};

export type GetHealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type GetHealthReadyErrors = {
    /**
     * The required database dependency is unavailable.
     */
    503: unknown;
};

export type GetHealthReadyResponses = {
    /**
     * The API and required database are ready.
     */
    200: unknown;
};

export type ListFavoritesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number.
         */
        page?: number;
        /**
         * Page size.
         */
        pageSize?: number;
    };
    url: '/api/v1/me/favorites';
};

export type ListFavoritesErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type ListFavoritesError = ListFavoritesErrors[keyof ListFavoritesErrors];

export type ListFavoritesResponses = {
    /**
     * Successfully listed.
     */
    200: {
        items: Array<{
            id: string;
            placeId: string;
            createdAt: string;
            place: {
                id: string;
                slug: string;
                name: string;
                shortDescription: string;
                city: string;
                category: string;
                ageSummary: string;
                coordinates: {
                    longitude: number;
                    latitude: number;
                };
                published: boolean;
                main_photo?: {
                    thumbnail_mini?: string;
                    thumbnail?: string;
                    card?: string;
                    hero?: string;
                    original_max?: string;
                } | null;
            };
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
    };
};

export type ListFavoritesResponse = ListFavoritesResponses[keyof ListFavoritesResponses];

export type GetPlaceStateData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Array of place UUIDs.
         */
        'placeIds[]'?: Array<string>;
    };
    url: '/api/v1/me/place-state';
};

export type GetPlaceStateErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type GetPlaceStateError = GetPlaceStateErrors[keyof GetPlaceStateErrors];

export type GetPlaceStateResponses = {
    /**
     * Successfully retrieved state.
     */
    200: {
        [key: string]: {
            favorite: boolean;
            lastVisitedOn: string | null;
        };
    };
};

export type GetPlaceStateResponse = GetPlaceStateResponses[keyof GetPlaceStateResponses];

export type ListVisitsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number.
         */
        page?: number;
        /**
         * Page size.
         */
        pageSize?: number;
    };
    url: '/api/v1/me/visits';
};

export type ListVisitsErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type ListVisitsError = ListVisitsErrors[keyof ListVisitsErrors];

export type ListVisitsResponses = {
    /**
     * Successfully listed.
     */
    200: {
        items: Array<{
            id: string;
            placeId: string;
            visitedOn: string;
            note: string | null;
            createdAt: string;
            updatedAt: string;
            place: {
                id: string;
                slug: string;
                name: string;
                shortDescription: string;
                city: string;
                category: string;
                ageSummary: string;
                coordinates: {
                    longitude: number;
                    latitude: number;
                };
                published: boolean;
                main_photo?: {
                    thumbnail_mini?: string;
                    thumbnail?: string;
                    card?: string;
                    hero?: string;
                    original_max?: string;
                } | null;
            };
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
    };
};

export type ListVisitsResponse = ListVisitsResponses[keyof ListVisitsResponses];

export type DeleteVisitData = {
    body?: never;
    path: {
        /**
         * Visit UUID.
         */
        visitId: string;
    };
    query?: never;
    url: '/api/v1/me/visits/{visitId}';
};

export type DeleteVisitErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Visit not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type DeleteVisitError = DeleteVisitErrors[keyof DeleteVisitErrors];

export type DeleteVisitResponses = {
    /**
     * Successfully deleted.
     */
    204: void;
};

export type DeleteVisitResponse = DeleteVisitResponses[keyof DeleteVisitResponses];

export type UpdateVisitData = {
    /**
     * Updated visit details.
     */
    body?: {
        visitedOn?: string;
        note?: string | null;
    };
    path: {
        /**
         * Visit UUID.
         */
        visitId: string;
    };
    query?: never;
    url: '/api/v1/me/visits/{visitId}';
};

export type UpdateVisitErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Visit not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type UpdateVisitError = UpdateVisitErrors[keyof UpdateVisitErrors];

export type UpdateVisitResponses = {
    /**
     * Successfully updated.
     */
    200: {
        id: string;
        placeId: string;
        visitedOn: string;
        note: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateVisitResponse = UpdateVisitResponses[keyof UpdateVisitResponses];

export type RemoveFavoriteData = {
    body?: never;
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: never;
    url: '/api/v1/places/{placeId}/favorite';
};

export type RemoveFavoriteErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type RemoveFavoriteError = RemoveFavoriteErrors[keyof RemoveFavoriteErrors];

export type RemoveFavoriteResponses = {
    /**
     * Successfully removed.
     */
    204: void;
};

export type RemoveFavoriteResponse = RemoveFavoriteResponses[keyof RemoveFavoriteResponses];

export type AddFavoriteData = {
    body?: never;
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: never;
    url: '/api/v1/places/{placeId}/favorite';
};

export type AddFavoriteErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Place not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type AddFavoriteError = AddFavoriteErrors[keyof AddFavoriteErrors];

export type AddFavoriteResponses = {
    /**
     * Successfully favorited.
     */
    200: {
        id: string;
        placeId: string;
        createdAt: string;
    };
};

export type AddFavoriteResponse = AddFavoriteResponses[keyof AddFavoriteResponses];

export type AddVisitData = {
    /**
     * Visit details.
     */
    body?: {
        visitedOn: string;
        note?: string | null;
    };
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: never;
    url: '/api/v1/places/{placeId}/visits';
};

export type AddVisitErrors = {
    /**
     * Invalid request payload.
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Place not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type AddVisitError = AddVisitErrors[keyof AddVisitErrors];

export type AddVisitResponses = {
    /**
     * Successfully created visit.
     */
    201: {
        id: string;
        placeId: string;
        visitedOn: string;
        note: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type AddVisitResponse = AddVisitResponses[keyof AddVisitResponses];
