// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type LoginWithGoogleData = {
    /**
     * Google ID token.
     */
    body?: {
        credential: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/google';
};

export type LoginWithGoogleErrors = {
    /**
     * Invalid Google credential.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Account link required.
     */
    409: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type LoginWithGoogleError = LoginWithGoogleErrors[keyof LoginWithGoogleErrors];

export type LoginWithGoogleResponses = {
    /**
     * Successfully authenticated.
     */
    200: {
        authenticated: boolean;
        user: {
            id: string;
            displayName: string;
            initials: string;
            roles: Array<string>;
        } | null;
        csrfToken: string | null;
    };
};

export type LoginWithGoogleResponse = LoginWithGoogleResponses[keyof LoginWithGoogleResponses];

export type LoginWithDevAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dev-auth/login';
};

export type LoginWithDevAuthErrors = {
    /**
     * Not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type LoginWithDevAuthError = LoginWithDevAuthErrors[keyof LoginWithDevAuthErrors];

export type LoginWithDevAuthResponses = {
    /**
     * Successfully authenticated.
     */
    200: {
        authenticated: boolean;
        user: {
            id: string;
            displayName: string;
            initials: string;
            roles: Array<string>;
        } | null;
        csrfToken: string | null;
    };
};

export type LoginWithDevAuthResponse = LoginWithDevAuthResponses[keyof LoginWithDevAuthResponses];

export type GetCommunityFeedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page limit.
         */
        limit?: number;
        /**
         * Pagination cursor.
         */
        cursor?: string;
        /**
         * Filter by activity type.
         */
        type?: string;
        /**
         * Filter by city UUID.
         */
        cityId?: string;
        /**
         * Filter by category UUID.
         */
        categoryId?: string;
    };
    url: '/api/v1/community/feed';
};

export type GetCommunityFeedResponses = {
    /**
     * Community activity feed.
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCommunityFeedResponse = GetCommunityFeedResponses[keyof GetCommunityFeedResponses];

export type DeleteCommentData = {
    body?: never;
    path: {
        /**
         * Comment UUID.
         */
        commentId: string;
    };
    query?: never;
    url: '/api/v1/me/place-comments/{commentId}';
};

export type DeleteCommentErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type DeleteCommentError = DeleteCommentErrors[keyof DeleteCommentErrors];

export type DeleteCommentResponses = {
    /**
     * Success (no content)
     */
    204: void;
};

export type DeleteCommentResponse = DeleteCommentResponses[keyof DeleteCommentResponses];

export type UpdateCommentData = {
    /**
     * Update comment body
     */
    body?: {
        body: string;
        version: number;
    };
    path: {
        /**
         * Comment UUID.
         */
        commentId: string;
    };
    query?: never;
    url: '/api/v1/me/place-comments/{commentId}';
};

export type UpdateCommentErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type UpdateCommentError = UpdateCommentErrors[keyof UpdateCommentErrors];

export type UpdateCommentResponses = {
    /**
     * Comment updated.
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateCommentResponse = UpdateCommentResponses[keyof UpdateCommentResponses];

export type MyReviewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number.
         */
        page?: number;
        /**
         * Page size.
         */
        pageSize?: number;
    };
    url: '/api/v1/me/reviews';
};

export type MyReviewsErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type MyReviewsError = MyReviewsErrors[keyof MyReviewsErrors];

export type MyReviewsResponses = {
    /**
     * My reviews list.
     */
    200: {
        [key: string]: unknown;
    };
};

export type MyReviewsResponse = MyReviewsResponses[keyof MyReviewsResponses];

export type DeleteReviewData = {
    body?: never;
    path: {
        /**
         * Review UUID.
         */
        reviewId: string;
    };
    query?: never;
    url: '/api/v1/me/reviews/{reviewId}';
};

export type DeleteReviewErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type DeleteReviewError = DeleteReviewErrors[keyof DeleteReviewErrors];

export type DeleteReviewResponses = {
    /**
     * Success (no content)
     */
    204: void;
};

export type DeleteReviewResponse = DeleteReviewResponses[keyof DeleteReviewResponses];

export type UpdateReviewData = {
    /**
     * Update review body
     */
    body?: {
        rating?: number;
        body?: string;
        visitedOn?: string | null;
        version: number;
    };
    path: {
        /**
         * Review UUID.
         */
        reviewId: string;
    };
    query?: never;
    url: '/api/v1/me/reviews/{reviewId}';
};

export type UpdateReviewErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type UpdateReviewError = UpdateReviewErrors[keyof UpdateReviewErrors];

export type UpdateReviewResponses = {
    /**
     * Review updated.
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateReviewResponse = UpdateReviewResponses[keyof UpdateReviewResponses];

export type AddReplyData = {
    /**
     * Reply body
     */
    body?: {
        body: string;
    };
    path: {
        /**
         * Parent comment UUID.
         */
        commentId: string;
    };
    query?: never;
    url: '/api/v1/place-comments/{commentId}/replies';
};

export type AddReplyErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type AddReplyError = AddReplyErrors[keyof AddReplyErrors];

export type AddReplyResponses = {
    /**
     * Reply created.
     */
    201: {
        [key: string]: unknown;
    };
};

export type AddReplyResponse = AddReplyResponses[keyof AddReplyResponses];

export type ListCommentsData = {
    body?: never;
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: {
        /**
         * Page number.
         */
        page?: number;
        /**
         * Page size.
         */
        pageSize?: number;
    };
    url: '/api/v1/places/{placeId}/comments';
};

export type ListCommentsResponses = {
    /**
     * List of comments.
     */
    200: {
        items: Array<{
            [key: string]: unknown;
        }>;
        pagination: {
            [key: string]: unknown;
        };
    };
};

export type ListCommentsResponse = ListCommentsResponses[keyof ListCommentsResponses];

export type AddCommentData = {
    /**
     * Comment body
     */
    body?: {
        body: string;
    };
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: never;
    url: '/api/v1/places/{placeId}/comments';
};

export type AddCommentErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type AddCommentError = AddCommentErrors[keyof AddCommentErrors];

export type AddCommentResponses = {
    /**
     * Comment created.
     */
    201: {
        [key: string]: unknown;
    };
};

export type AddCommentResponse = AddCommentResponses[keyof AddCommentResponses];

export type ListReviewsData = {
    body?: never;
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: {
        /**
         * Page number.
         */
        page?: number;
        /**
         * Page size.
         */
        pageSize?: number;
        /**
         * Sort parameter.
         */
        sort?: 'newest' | 'highest' | 'lowest';
    };
    url: '/api/v1/places/{placeId}/reviews';
};

export type ListReviewsResponses = {
    /**
     * List of reviews.
     */
    200: {
        summary: {
            averageRating: number;
            totalReviews: number;
            histogram: {
                [key: string]: unknown;
            };
        };
        items: Array<{
            [key: string]: unknown;
        }>;
        pagination: {
            [key: string]: unknown;
        };
    };
};

export type ListReviewsResponse = ListReviewsResponses[keyof ListReviewsResponses];

export type AddReviewData = {
    /**
     * Review body
     */
    body?: {
        rating: number;
        body: string;
        visitedOn?: string | null;
    };
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: never;
    url: '/api/v1/places/{placeId}/reviews';
};

export type AddReviewErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type AddReviewError = AddReviewErrors[keyof AddReviewErrors];

export type AddReviewResponses = {
    /**
     * Review created.
     */
    201: {
        [key: string]: unknown;
    };
};

export type AddReviewResponse = AddReviewResponses[keyof AddReviewResponses];

export type GetAmenitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/amenities';
};

export type GetAmenitiesResponses = {
    /**
     * Reference collection.
     */
    200: {
        items: Array<{
            id: string;
            name: string;
            slug: string;
            icon_key: string;
            display_order: number;
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        meta: {
            [key: string]: unknown;
        };
    };
};

export type GetAmenitiesResponse = GetAmenitiesResponses[keyof GetAmenitiesResponses];

export type GetCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/categories';
};

export type GetCategoriesResponses = {
    /**
     * Reference collection.
     */
    200: {
        items: Array<{
            id: string;
            name: string;
            slug: string;
            icon_key: string;
            display_order: number;
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        meta: {
            [key: string]: unknown;
        };
    };
};

export type GetCategoriesResponse = GetCategoriesResponses[keyof GetCategoriesResponses];

export type GetCitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cities';
};

export type GetCitiesResponses = {
    /**
     * Reference collection.
     */
    200: {
        items: Array<{
            id: string;
            name: string;
            slug: string;
            country_code: string;
            default_zoom: number;
            default_radius_km: number;
            timezone: string;
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        meta: {
            [key: string]: unknown;
        };
    };
};

export type GetCitiesResponse = GetCitiesResponses[keyof GetCitiesResponses];

export type GetMapPlacesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * west filter.
         */
        west: number;
        /**
         * south filter.
         */
        south: number;
        /**
         * east filter.
         */
        east: number;
        /**
         * north filter.
         */
        north: number;
        /**
         * zoom filter.
         */
        zoom: number;
        /**
         * city filter.
         */
        city?: string;
        /**
         * category filter.
         */
        category?: string;
        /**
         * ageMonths filter.
         */
        ageMonths?: number;
        /**
         * latitude filter.
         */
        latitude?: number;
        /**
         * longitude filter.
         */
        longitude?: number;
        /**
         * radiusKm filter.
         */
        radiusKm?: number;
        /**
         * amenities filter.
         */
        amenities?: Array<string>;
        /**
         * indoor filter.
         */
        indoor?: boolean;
        /**
         * outdoor filter.
         */
        outdoor?: boolean;
        /**
         * freeEntry filter.
         */
        freeEntry?: boolean;
        /**
         * openNow filter.
         */
        openNow?: boolean;
        /**
         * q filter.
         */
        q?: string;
        /**
         * page filter.
         */
        page?: number;
        /**
         * pageSize filter.
         */
        pageSize?: number;
        /**
         * sort filter.
         */
        sort?: string;
    };
    url: '/api/v1/map/places';
};

export type GetMapPlacesErrors = {
    /**
     * RFC 9457 invalid_query Problem Details.
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * RFC 9457 rate_limit_exceeded Problem Details with Retry-After.
     */
    429: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type GetMapPlacesError = GetMapPlacesErrors[keyof GetMapPlacesErrors];

export type GetMapPlacesResponses = {
    /**
     * GeoJSON FeatureCollection, at most 500 features.
     */
    200: {
        type: 'FeatureCollection';
        truncated: boolean;
        features: Array<{
            type: 'Feature';
            geometry: {
                type?: string;
                coordinates?: [
                    number,
                    number
                ];
            };
            properties: {
                slug: string;
                name: string;
                indoor: boolean;
                outdoor: boolean;
                freeEntry: boolean;
            };
        }>;
    };
};

export type GetMapPlacesResponse = GetMapPlacesResponses[keyof GetMapPlacesResponses];

export type SearchPlacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * city filter.
         */
        city?: string;
        /**
         * category filter.
         */
        category?: string;
        /**
         * ageMonths filter.
         */
        ageMonths?: number;
        /**
         * latitude filter.
         */
        latitude?: number;
        /**
         * longitude filter.
         */
        longitude?: number;
        /**
         * radiusKm filter.
         */
        radiusKm?: number;
        /**
         * amenities filter.
         */
        amenities?: Array<string>;
        /**
         * indoor filter.
         */
        indoor?: boolean;
        /**
         * outdoor filter.
         */
        outdoor?: boolean;
        /**
         * freeEntry filter.
         */
        freeEntry?: boolean;
        /**
         * openNow filter.
         */
        openNow?: boolean;
        /**
         * q filter.
         */
        q?: string;
        /**
         * page filter.
         */
        page?: number;
        /**
         * pageSize filter.
         */
        pageSize?: number;
        /**
         * sort filter.
         */
        sort?: string;
    };
    url: '/api/v1/places';
};

export type SearchPlacesErrors = {
    /**
     * RFC 9457 invalid_query Problem Details.
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * RFC 9457 rate_limit_exceeded Problem Details with Retry-After.
     */
    429: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type SearchPlacesError = SearchPlacesErrors[keyof SearchPlacesErrors];

export type SearchPlacesResponses = {
    /**
     * Paginated place cards.
     */
    200: {
        items: Array<{
            id: string;
            slug: string;
            name: string;
            short_description: string;
            city: string;
            categories: Array<{
                slug: string;
                name: string;
            }>;
            min_age_months: number;
            max_age_months: number | null;
            indoor: boolean;
            outdoor: boolean;
            free_entry: boolean;
            verification_status: string;
            amenities: Array<{
                slug: string;
                name: string;
            }>;
            distance_meters: number | null;
            longitude: number;
            latitude: number;
            is_open_now: boolean | null;
            complete: boolean;
            relevance_score: number;
            average_rating: number;
            total_reviews: number;
            main_photo?: {
                thumbnail_mini?: string;
                thumbnail?: string;
                card?: string;
                hero?: string;
                original_max?: string;
            } | null;
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
        meta: {
            sort: string;
        };
    };
};

export type SearchPlacesResponse = SearchPlacesResponses[keyof SearchPlacesResponses];

export type GetPlaceBySlugData = {
    body?: never;
    path: {
        /**
         * Published place slug.
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/places/{slug}';
};

export type GetPlaceBySlugErrors = {
    /**
     * RFC 9457 place_not_found Problem Details.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type GetPlaceBySlugError = GetPlaceBySlugErrors[keyof GetPlaceBySlugErrors];

export type GetPlaceBySlugResponses = {
    /**
     * Published place details.
     */
    200: {
        id: string;
        slug: string;
        name: string;
        short_description: string;
        description: string;
        city_name: string;
        city_slug: string;
        address_line1: string;
        address_line2: string | null;
        postal_code: string;
        country_code: string;
        categories: Array<{
            slug: string;
            name: string;
        }>;
        amenities: Array<{
            slug: string;
            name: string;
        }>;
        age_zones: Array<{
            [key: string]: unknown;
        }>;
        weekly_opening: Array<{
            [key: string]: unknown;
        }>;
        special_opening: Array<{
            [key: string]: unknown;
        }>;
        ageZones: Array<{
            minAgeMonths: number;
            maxAgeMonths: number | null;
            label: string;
        }>;
        openingSchedule: Array<{
            dayOfWeek: number;
            closed: boolean;
            periods: Array<{
                opensAt: string;
                closesAt: string;
                closesNextDay: boolean;
            }>;
        }>;
        specialOpeningDays: Array<{
            date: string;
            mode: string;
            note: string | null;
            periods: Array<{
                opensAt: string;
                closesAt: string;
                closesNextDay: boolean;
            }>;
        }>;
        indoor: boolean;
        outdoor: boolean;
        free_entry: boolean;
        price_description: string | null;
        website_url: string | null;
        phone: string | null;
        verification_status: string;
        longitude: number;
        latitude: number;
        main_photo?: {
            thumbnail_mini?: string;
            thumbnail?: string;
            card?: string;
            hero?: string;
            original_max?: string;
        } | null;
        photos?: Array<{
            id?: string;
            is_main?: boolean;
            alt_text?: string | null;
            caption?: string | null;
            variants?: {
                thumbnail_mini?: string;
                thumbnail?: string;
                card?: string;
                hero?: string;
                original_max?: string;
            };
        }>;
    };
};

export type GetPlaceBySlugResponse = GetPlaceBySlugResponses[keyof GetPlaceBySlugResponses];

export type ListForumCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/forum/categories';
};

export type ListForumCategoriesResponses = {
    /**
     * Forum categories list.
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type ListForumCategoriesResponse = ListForumCategoriesResponses[keyof ListForumCategoriesResponses];

export type CreateForumThreadData = {
    /**
     * Thread content
     */
    body?: {
        title: string;
        body: string;
    };
    path: {
        /**
         * Category UUID.
         */
        categoryId: string;
    };
    query?: never;
    url: '/api/v1/forum/categories/{categoryId}/threads';
};

export type CreateForumThreadResponses = {
    /**
     * Thread created.
     */
    201: {
        [key: string]: unknown;
    };
};

export type CreateForumThreadResponse = CreateForumThreadResponses[keyof CreateForumThreadResponses];

export type ListCategoryThreadsData = {
    body?: never;
    path: {
        /**
         * Category slug.
         */
        slug: string;
    };
    query?: {
        /**
         * Page limit.
         */
        limit?: number;
        /**
         * Pagination cursor.
         */
        cursor?: string;
    };
    url: '/api/v1/forum/categories/{slug}/threads';
};

export type ListCategoryThreadsResponses = {
    /**
     * Category threads list.
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListCategoryThreadsResponse = ListCategoryThreadsResponses[keyof ListCategoryThreadsResponses];

export type GetForumThreadData = {
    body?: never;
    path: {
        /**
         * Thread UUID.
         */
        threadId: string;
    };
    query?: never;
    url: '/api/v1/forum/threads/{threadId}';
};

export type GetForumThreadResponses = {
    /**
     * Thread detail.
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetForumThreadResponse = GetForumThreadResponses[keyof GetForumThreadResponses];

export type ListForumPostsData = {
    body?: never;
    path: {
        /**
         * Thread UUID.
         */
        threadId: string;
    };
    query?: {
        /**
         * Page limit.
         */
        limit?: number;
        /**
         * Pagination cursor.
         */
        cursor?: string;
    };
    url: '/api/v1/forum/threads/{threadId}/posts';
};

export type ListForumPostsResponses = {
    /**
     * Posts list.
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListForumPostsResponse = ListForumPostsResponses[keyof ListForumPostsResponses];

export type CreateForumPostData = {
    /**
     * Post body
     */
    body?: {
        body: string;
        replyToPostId?: string;
    };
    path: {
        /**
         * Thread UUID.
         */
        threadId: string;
    };
    query?: never;
    url: '/api/v1/forum/threads/{threadId}/posts';
};

export type CreateForumPostResponses = {
    /**
     * Post created.
     */
    201: {
        [key: string]: unknown;
    };
};

export type CreateForumPostResponse = CreateForumPostResponses[keyof CreateForumPostResponses];

export type DeleteOwnForumPostData = {
    body?: never;
    path: {
        /**
         * Post UUID.
         */
        postId: string;
    };
    query?: never;
    url: '/api/v1/me/forum-posts/{postId}';
};

export type DeleteOwnForumPostResponses = {
    /**
     * Success (no content)
     */
    204: void;
};

export type DeleteOwnForumPostResponse = DeleteOwnForumPostResponses[keyof DeleteOwnForumPostResponses];

export type EditOwnForumPostData = {
    /**
     * Edit post body
     */
    body?: {
        body: string;
        version: number;
    };
    path: {
        /**
         * Post UUID.
         */
        postId: string;
    };
    query?: never;
    url: '/api/v1/me/forum-posts/{postId}';
};

export type EditOwnForumPostResponses = {
    /**
     * Post updated.
     */
    200: {
        [key: string]: unknown;
    };
};

export type EditOwnForumPostResponse = EditOwnForumPostResponses[keyof EditOwnForumPostResponses];

export type DeleteOwnForumThreadData = {
    body?: never;
    path: {
        /**
         * Thread UUID.
         */
        threadId: string;
    };
    query?: never;
    url: '/api/v1/me/forum-threads/{threadId}';
};

export type DeleteOwnForumThreadResponses = {
    /**
     * Success (no content)
     */
    204: void;
};

export type DeleteOwnForumThreadResponse = DeleteOwnForumThreadResponses[keyof DeleteOwnForumThreadResponses];

export type EditOwnForumThreadData = {
    /**
     * Edit thread body
     */
    body?: {
        title: string;
        version: number;
    };
    path: {
        /**
         * Thread UUID.
         */
        threadId: string;
    };
    query?: never;
    url: '/api/v1/me/forum-threads/{threadId}';
};

export type EditOwnForumThreadResponses = {
    /**
     * Thread updated.
     */
    200: {
        [key: string]: unknown;
    };
};

export type EditOwnForumThreadResponse = EditOwnForumThreadResponses[keyof EditOwnForumThreadResponses];

export type GetHealthLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type GetHealthLiveResponses = {
    /**
     * The API process is alive.
     */
    200: unknown;
};

export type GetHealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type GetHealthReadyErrors = {
    /**
     * The required database dependency is unavailable.
     */
    503: unknown;
};

export type GetHealthReadyResponses = {
    /**
     * The API and required database are ready.
     */
    200: unknown;
};

export type ReportContentData = {
    /**
     * Report details
     */
    body?: {
        targetId: string;
        targetType: 'REVIEW' | 'PLACE_COMMENT' | 'FORUM_THREAD' | 'FORUM_POST';
        reason: 'SPAM' | 'HARASSMENT' | 'INAPPROPRIATE' | 'MISINFORMATION' | 'PRIVACY_CONCERN' | 'OTHER';
        details?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/content-reports';
};

export type ReportContentResponses = {
    /**
     * Report created.
     */
    201: {
        [key: string]: unknown;
    };
};

export type ReportContentResponse = ReportContentResponses[keyof ReportContentResponses];

export type ModerateContentData = {
    /**
     * Moderation action details
     */
    body?: {
        targetId: string;
        targetType: 'REVIEW' | 'PLACE_COMMENT' | 'FORUM_THREAD' | 'FORUM_POST';
        action: 'HIDE' | 'REMOVE' | 'RESTORE' | 'LOCK' | 'UNLOCK' | 'PIN' | 'UNPIN' | 'DISMISS_REPORT' | 'RESOLVE_REPORT';
        reason: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/moderation/action';
};

export type ModerateContentResponses = {
    /**
     * Perform moderator action.
     */
    200: {
        [key: string]: unknown;
    };
};

export type ModerateContentResponse = ModerateContentResponses[keyof ModerateContentResponses];

export type ListModerationQueueData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by report status.
         */
        status?: string;
        /**
         * Page number.
         */
        page?: number;
        /**
         * Page size.
         */
        pageSize?: number;
    };
    url: '/api/v1/moderation/queue';
};

export type ListModerationQueueResponses = {
    /**
     * Moderation queue reports list.
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListModerationQueueResponse = ListModerationQueueResponses[keyof ListModerationQueueResponses];

export type ListFavoritesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number.
         */
        page?: number;
        /**
         * Page size.
         */
        pageSize?: number;
    };
    url: '/api/v1/me/favorites';
};

export type ListFavoritesErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type ListFavoritesError = ListFavoritesErrors[keyof ListFavoritesErrors];

export type ListFavoritesResponses = {
    /**
     * Successfully listed.
     */
    200: {
        items: Array<{
            id: string;
            placeId: string;
            createdAt: string;
            place: {
                id: string;
                slug: string;
                name: string;
                shortDescription: string;
                city: string;
                category: string;
                ageSummary: string;
                coordinates: {
                    longitude: number;
                    latitude: number;
                };
                published: boolean;
                main_photo?: {
                    thumbnail_mini?: string;
                    thumbnail?: string;
                    card?: string;
                    hero?: string;
                    original_max?: string;
                } | null;
            };
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
    };
};

export type ListFavoritesResponse = ListFavoritesResponses[keyof ListFavoritesResponses];

export type GetPlaceStateData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Array of place UUIDs.
         */
        'placeIds[]'?: Array<string>;
    };
    url: '/api/v1/me/place-state';
};

export type GetPlaceStateErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type GetPlaceStateError = GetPlaceStateErrors[keyof GetPlaceStateErrors];

export type GetPlaceStateResponses = {
    /**
     * Successfully retrieved state.
     */
    200: {
        [key: string]: {
            favorite: boolean;
            lastVisitedOn: string | null;
        };
    };
};

export type GetPlaceStateResponse = GetPlaceStateResponses[keyof GetPlaceStateResponses];

export type ListVisitsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number.
         */
        page?: number;
        /**
         * Page size.
         */
        pageSize?: number;
    };
    url: '/api/v1/me/visits';
};

export type ListVisitsErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type ListVisitsError = ListVisitsErrors[keyof ListVisitsErrors];

export type ListVisitsResponses = {
    /**
     * Successfully listed.
     */
    200: {
        items: Array<{
            id: string;
            placeId: string;
            visitedOn: string;
            note: string | null;
            createdAt: string;
            updatedAt: string;
            place: {
                id: string;
                slug: string;
                name: string;
                shortDescription: string;
                city: string;
                category: string;
                ageSummary: string;
                coordinates: {
                    longitude: number;
                    latitude: number;
                };
                published: boolean;
                main_photo?: {
                    thumbnail_mini?: string;
                    thumbnail?: string;
                    card?: string;
                    hero?: string;
                    original_max?: string;
                } | null;
            };
        }>;
        pagination: {
            page: number;
            pageSize: number;
            totalItems: number;
            totalPages: number;
        };
    };
};

export type ListVisitsResponse = ListVisitsResponses[keyof ListVisitsResponses];

export type DeleteVisitData = {
    body?: never;
    path: {
        /**
         * Visit UUID.
         */
        visitId: string;
    };
    query?: never;
    url: '/api/v1/me/visits/{visitId}';
};

export type DeleteVisitErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Visit not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type DeleteVisitError = DeleteVisitErrors[keyof DeleteVisitErrors];

export type DeleteVisitResponses = {
    /**
     * Successfully deleted.
     */
    204: void;
};

export type DeleteVisitResponse = DeleteVisitResponses[keyof DeleteVisitResponses];

export type UpdateVisitData = {
    /**
     * Updated visit details.
     */
    body?: {
        visitedOn?: string;
        note?: string | null;
    };
    path: {
        /**
         * Visit UUID.
         */
        visitId: string;
    };
    query?: never;
    url: '/api/v1/me/visits/{visitId}';
};

export type UpdateVisitErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Visit not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type UpdateVisitError = UpdateVisitErrors[keyof UpdateVisitErrors];

export type UpdateVisitResponses = {
    /**
     * Successfully updated.
     */
    200: {
        id: string;
        placeId: string;
        visitedOn: string;
        note: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type UpdateVisitResponse = UpdateVisitResponses[keyof UpdateVisitResponses];

export type RemoveFavoriteData = {
    body?: never;
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: never;
    url: '/api/v1/places/{placeId}/favorite';
};

export type RemoveFavoriteErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type RemoveFavoriteError = RemoveFavoriteErrors[keyof RemoveFavoriteErrors];

export type RemoveFavoriteResponses = {
    /**
     * Successfully removed.
     */
    204: void;
};

export type RemoveFavoriteResponse = RemoveFavoriteResponses[keyof RemoveFavoriteResponses];

export type AddFavoriteData = {
    body?: never;
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: never;
    url: '/api/v1/places/{placeId}/favorite';
};

export type AddFavoriteErrors = {
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Place not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type AddFavoriteError = AddFavoriteErrors[keyof AddFavoriteErrors];

export type AddFavoriteResponses = {
    /**
     * Successfully favorited.
     */
    200: {
        id: string;
        placeId: string;
        createdAt: string;
    };
};

export type AddFavoriteResponse = AddFavoriteResponses[keyof AddFavoriteResponses];

export type AddVisitData = {
    /**
     * Visit details.
     */
    body?: {
        visitedOn: string;
        note?: string | null;
    };
    path: {
        /**
         * Place UUID.
         */
        placeId: string;
    };
    query?: never;
    url: '/api/v1/places/{placeId}/visits';
};

export type AddVisitErrors = {
    /**
     * Invalid request payload.
     */
    400: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Unauthorized.
     */
    401: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
    /**
     * Place not found.
     */
    404: {
        type: string;
        title: string;
        status: number;
        detail: string;
        code: string;
        correlationId: string;
    };
};

export type AddVisitError = AddVisitErrors[keyof AddVisitErrors];

export type AddVisitResponses = {
    /**
     * Successfully created visit.
     */
    201: {
        id: string;
        placeId: string;
        visitedOn: string;
        note: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type AddVisitResponse = AddVisitResponses[keyof AddVisitResponses];
